# Generated by Django 3.1.7 on 2021-03-22 16:40

import SchoolManagement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('3', 'difficult'), ('2', 'general')], max_length=10, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SchoolManagement.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='question '),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(upload_to=SchoolManagement.models.content_file_name),
        ),
    ]
