# Generated by Django 3.1.7 on 2021-03-20 20:49

import SchoolManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'general'), ('3', 'difficult'), ('1', 'easy')], max_length=10, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(upload_to=SchoolManagement.models.content_file_name),
        ),
    ]
