# Generated by Django 3.1.7 on 2021-03-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManagement', '0003_auto_20210322_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SchoolManagement.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'general'), ('1', 'easy'), ('3', 'difficult')], max_length=10, verbose_name='level'),
        ),
    ]
